force-app/main/default/objects/GC_Tier__c/GC_Tier__c.object-meta.xml
<CustomObject>
    <label>GC Tier</label>
    <nameField>
        <label>Graduated Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GC Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GC_Tier__c/fields/GCT_Target_Achieved_High__c.field-meta.xml
<CustomField>
    <fullName>GCT_Target_Achieved_High__c</fullName>
    <label>Target Achieved High</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/GC_Tier__c/fields/GCT_Target_Achieved_Low__c.field-meta.xml
<CustomField>
    <fullName>GCT_Target_Achieved_Low__c</fullName>
    <label>Target Achieved Low</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/GC_Tier__c/fields/GCT_Target_Earned_Rate__c.field-meta.xml
<CustomField>
    <fullName>GCT_Target_Earned_Rate__c</fullName>
    <label>Target Earned Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GC_Tier__c/fields/Graduated_Commission__c.field-meta.xml
<CustomField>
    <fullName>Graduated_Commission__c</fullName>
    <label>Graduated Commission</label>
    <referenceTo>NC_Graduated_Commission__c</referenceTo>
    <relationshipLabel>GC Tiers</relationshipLabel>
    <relationshipName>GC_Tiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NC_Graduated_Commission__c/NC_Graduated_Commission__c.object-meta.xml
<CustomObject>
    <label>Graduated Commission</label>
    <nameField>
        <displayFormat>GC-{0000}</displayFormat>
        <label>Graduated Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduated Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduated Commissions</relationshipLabel>
    <relationshipName>Graduated_Commissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/GC_End_Date__c.field-meta.xml
<CustomField>
    <fullName>GC_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/GC_Goal__c.field-meta.xml
<CustomField>
    <fullName>GC_Goal__c</fullName>
    <label>Goal Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/GD_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>GD_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/NC_Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Lease__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lease</relationshipLabel>
    <relationshipName>Lease</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/Graduated_Commission__c.field-meta.xml
<CustomField>
    <fullName>Graduated_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Graduated Commission</label>
    <referenceTo>NC_Graduated_Commission__c</referenceTo>
    <relationshipLabel>Lease</relationshipLabel>
    <relationshipName>Lease</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/L_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>L_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NC_Graduated_Commission.cls
/**
 * @File Name          : NC_Graduated_Commission.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 2019-08-12, 10:30:12 p.m.
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    2019-08-11, 8:21:51 a.m.   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class NC_Graduated_Commission {


    /**
    *   Return the Graduated Commission based on the Lease period of date
    * */
    public static NC_Graduated_Commission__c getCurrentGraduatedCommission(NC_Lease__c lease){

        NC_Graduated_Commission__c gc = [select id, GC_Goal__c, Contact__c, GD_Start_Date__c, GC_End_Date__c from NC_Graduated_Commission__c where GD_Start_Date__c <= :lease.L_Start_Date__c and GC_End_Date__c > :lease.L_Start_Date__c and Contact__c = :lease.Contact__c Limit 1 ];

        return gc;
        
    }

    public static Decimal calculateCommission(NC_Lease__c lease){

        NC_Graduated_Commission__c gc = getCurrentGraduatedCommission(lease);
        
        Decimal currenttotal = NC_Lease.getAllRevenueByContact(gc);

        Decimal accumulatedPercentage = (currenttotal * 100)/gc.GC_Goal__c;

        List<GC_Tier__c> selectedTiers = [select id, gct_target_earned_rate__c from gc_tier__c where Graduated_Commission__c = :gc.Id and gct_target_achieved_low__c <=:accumulatedPercentage and gct_target_achieved_high__c > :accumulatedPercentage ];
        
        Decimal earnedRate = (selectedTiers.size() > 0)?(decimal) selectedTiers[0].gct_target_earned_rate__c: 0;
        
        return (Decimal) (accumulatedPercentage * earnedRate).setScale(2);

    }
    
    /**
     * 
     * This validates the overlapping Dates
     * One Record per Contact per Period
     * */
    public static List<NC_Graduated_Commission__c> isValid(List<NC_Graduated_Commission__c> newGC){
        

            List<NC_Graduated_Commission__c> existGC = [Select id, Contact__c, GD_Start_Date__c, GC_End_Date__c from NC_Graduated_Commission__c];
            
            List<NC_Graduated_Commission__c>  checkedOverlap = haskOverlap(existGC, newGC);
            
 
        return checkedOverlap;
       
    }
    
    public static List<NC_Graduated_Commission__c> haskOverlap(List<NC_Graduated_Commission__c> existGCs, List<NC_Graduated_Commission__c> newGCs){
        
        
        List<NC_Graduated_Commission__c> gcErrorList = new List<NC_Graduated_Commission__c>();
        
             for (NC_Graduated_Commission__c existGC : existGCs) {
                for (NC_Graduated_Commission__c newGC : newGCs) {

                    if (
                        existGC.Contact__c == newGC.Contact__c &&
                        (
                            (
                                newGC.GD_Start_Date__c >= existGC.GD_Start_Date__c &&
                                newGC.GD_Start_Date__c <= existGC.GC_End_Date__c
                            ) ||
                            (
                                newGC.GC_End_Date__c >= existGC.GD_Start_Date__c &&
                                newGC.GC_End_Date__c <= existGC.GC_End_Date__c
                            )
                        )
                    ) {
                        System.debug('nc2.3>>'+newGC);
                        newGC.addError('The Contact already has a Graduated Commission on specified dates!');
                        
                        gcErrorList.add(newGC);

                    }
                }
            }
        
        return gcErrorList;
    }
}