force-app/main/default/objects/GC_Tier__c/GC_Tier__c.object-meta.xml
<CustomObject>
    <label>GC Tier</label>
    <nameField>
        <label>Graduated Commission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GC Tiers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GC_Tier__c/fields/GCT_Target_Achieved_High__c.field-meta.xml
<CustomField>
    <fullName>GCT_Target_Achieved_High__c</fullName>
    <label>Target Achieved High</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/GC_Tier__c/fields/GCT_Target_Achieved_Low__c.field-meta.xml
<CustomField>
    <fullName>GCT_Target_Achieved_Low__c</fullName>
    <label>Target Achieved Low</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/GC_Tier__c/fields/GCT_Target_Earned_Rate__c.field-meta.xml
<CustomField>
    <fullName>GCT_Target_Earned_Rate__c</fullName>
    <label>Target Earned Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/GC_Tier__c/fields/Graduated_Commission__c.field-meta.xml
<CustomField>
    <fullName>Graduated_Commission__c</fullName>
    <label>Graduated Commission</label>
    <referenceTo>NC_Graduated_Commission__c</referenceTo>
    <relationshipLabel>GC Tiers</relationshipLabel>
    <relationshipName>GC_Tiers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NC_Bounty__c/NC_Bounty__c.object-meta.xml
<CustomObject>
    <label>Bounty</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Bounty Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bounties</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Bounty__c/fields/B_End_Date__c.field-meta.xml
<CustomField>
    <fullName>B_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Bounty__c/fields/B_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>B_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Bounty__c/fields/Measure_Unit__c.field-meta.xml
<CustomField>
    <fullName>Measure_Unit__c</fullName>
    <label>Measure Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Percent</fullName>
            </value>
            <value>
                <fullName>Fixed quantity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NC_Bounty__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>NC_Unit__c</referenceTo>
    <relationshipLabel>Bounties</relationshipLabel>
    <relationshipName>Bounties</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NC_Graduated_Commission__c/NC_Graduated_Commission__c.object-meta.xml
<CustomObject>
    <label>Graduated Commission</label>
    <nameField>
        <displayFormat>GC-{0000}</displayFormat>
        <label>Graduated Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduated Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduated Commissions</relationshipLabel>
    <relationshipName>Graduated_Commissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/GC_End_Date__c.field-meta.xml
<CustomField>
    <fullName>GC_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/GC_Goal__c.field-meta.xml
<CustomField>
    <fullName>GC_Goal__c</fullName>
    <label>Goal Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/GD_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>GD_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/NC_Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Lease__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lease</relationshipLabel>
    <relationshipName>Lease</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/Graduated_Commission__c.field-meta.xml
<CustomField>
    <fullName>Graduated_Commission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Graduated Commission</label>
    <referenceTo>NC_Graduated_Commission__c</referenceTo>
    <relationshipLabel>Lease</relationshipLabel>
    <relationshipName>Lease</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/L_Amount__c.field-meta.xml
<CustomField>
    <fullName>L_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/L_End_Date__c.field-meta.xml
<CustomField>
    <fullName>L_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/L_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>L_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>NC_Unit__c</referenceTo>
    <relationshipLabel>Lease</relationshipLabel>
    <relationshipName>Lease</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NC_Property__c/NC_Property__c.object-meta.xml
<CustomObject>
    <label>Property</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Property Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Unit__c/NC_Unit__c.object-meta.xml
<CustomObject>
    <description>Unit for property</description>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Unit__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>NC_Property__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NC_Unit__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>Cost per day</description>
    <inlineHelpText>Enter cost per day</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**
 * @File Name          : TestDataFactory.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 2019-08-13, 2:15:55 p.m.
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    2019-08-13, 2:15:55 p.m.   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
@isTest
public class TestDataFactory {
    

    public static NC_Graduated_Commission__c createGC(Contact c){
        
        NC_Graduated_Commission__c gc = new NC_Graduated_Commission__c();
        gc.GD_Start_Date__c = Date.valueOf('2019-01-01');
        gc.GC_End_Date__c	= Date.valueOf('2019-12-31');
        gc.Contact__c		= c.Id;
        gc.GC_Goal__c		= 2000000;
        
        insert gc;
        
        GC_Tier__c t1 = new  GC_Tier__c();
        t1.GCT_Target_Achieved_Low__c 	= 25;
        t1.GCT_Target_Achieved_High__c 	= 50;
        t1.GCT_Target_Earned_Rate__c	= 100;
        t1.Graduated_Commission__c		= gc.Id;
        
        insert t1;
        
        GC_Tier__c t2 = new  GC_Tier__c();
        t2.GCT_Target_Achieved_Low__c 	= 50;
        t2.GCT_Target_Achieved_High__c 	= 75;
        t2.GCT_Target_Earned_Rate__c	= 150;
        t2.Graduated_Commission__c		= gc.Id;
        
        insert t2;
       
        GC_Tier__c t3 = new  GC_Tier__c();
        t3.GCT_Target_Achieved_Low__c 	= 75;
        t3.GCT_Target_Achieved_High__c 	= 100;
        t3.GCT_Target_Earned_Rate__c	= 200;
        t3.Graduated_Commission__c		= gc.Id;
        
        insert t3;
        
        return gc;
        
    }
    

    public static Contact createContact(){
        
        Contact c = new Contact(FirstName = 'Pedro', LastName='Garcia');

        insert c;
        
        return c;
 
    }
    
  
    public static List<NC_Lease__c> createLeaseList(){
        
        Contact c = createContact();
        NC_Unit__c u = createUnitAProperty(c);
        
        NC_Graduated_Commission__c gc = createGC(c);
        
        List<NC_Lease__c> lList = New List<NC_Lease__c>();

        NC_Lease__c l1 = new NC_Lease__c();

        l1.L_Start_Date__c 	= Date.valueOf('2019-01-01');
        l1.L_End_Date__c 	= Date.valueOf('2019-05-31');
        l1.Graduated_Commission__c = gc.Id;
        l1.Unit__c = u.Id;
        //l1.L_Amount__c	= 20000;

        lList.add(l1);

        NC_Lease__c l2 = new NC_Lease__c();
        l2.L_Start_Date__c 	= Date.valueOf('2019-06-01');
        l2.L_End_Date__c 	= Date.valueOf('2019-12-30');
        l2.Graduated_Commission__c = gc.Id;
        l2.Unit__c = u.Id;
       	//l2.L_Amount__c	= NC_Lease.calculateTotalCost( l2);
		//l2.L_Amount__c	= 40000;
        
        //lList.add(l2);
        
        insert lList;
        
        return lList;
    }
    
   
    public static NC_Unit__c createUnitAProperty(Contact c){
        
        NC_Property__c p = new NC_Property__c();

        p.Contact__c = c.Id;

        insert p;

        NC_Unit__c u = new NC_Unit__c();
        u.Property__c = p.Id;
        u.Revenue__c  = 2200;
        
        insert u;
        
        NC_Bounty__c b = new NC_Bounty__c();
        b.Unit__c = u.Id;
        b.B_Start_Date__c 	= Date.valueOf('2019-01-01');
        b.B_End_Date__c		= Date.valueOf('2019-07-01');
        b.Value__c			= 300;
        b.Measure_Unit__c	= 'Fixed quantity';
        
        insert b;
        
        return u;
    }

}