force-app/main/default/objects/NC_Graduated_Commission__c/NC_Graduated_Commission__c.object-meta.xml
<CustomObject>
    <label>Graduated Commission</label>
    <nameField>
        <displayFormat>GC-{0000}</displayFormat>
        <label>Graduated Commission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Graduated Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Graduated Commissions</relationshipLabel>
    <relationshipName>Graduated_Commissions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NC_Graduated_Commission__c/fields/GD_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>GD_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/NC_Lease__c.object-meta.xml
<CustomObject>
    <label>Lease</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>Lease Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lease</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Lease__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Lease</relationshipLabel>
    <relationshipName>Lease</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/L_Amount__c.field-meta.xml
<CustomField>
    <fullName>L_Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/L_End_Date__c.field-meta.xml
<CustomField>
    <fullName>L_End_Date__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/L_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>L_Start_Date__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/NC_Lease__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>NC_Unit__c</referenceTo>
    <relationshipLabel>Lease</relationshipLabel>
    <relationshipName>Lease</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NC_Unit__c/NC_Unit__c.object-meta.xml
<CustomObject>
    <description>Unit for property</description>
    <label>Unit</label>
    <nameField>
        <displayFormat>U-{0000}</displayFormat>
        <label>Unit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NC_Unit__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>Cost per day</description>
    <inlineHelpText>Enter cost per day</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/NC_Lease.cls
/**
 * @File Name          : NC_Lease.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 2019-08-12, 4:29:41 p.m.
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    2019-08-10, 1:54:10 p.m.   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class NC_Lease {
    public NC_Lease() {

    }

    



    public static Decimal getAllRevenueByContact(NC_Graduated_Commission__c gc){

        List<AggregateResult> agLease = [Select SUM(L_Amount__c) amountSum from NC_Lease__c where L_Start_Date__c <= :gc.GD_Start_Date__c and L_End_Date__c > :gc.GD_Start_Date__c and Contact__c =: gc.Contact__c];

        Decimal currentTotal = 0;

        for (AggregateResult ar : agLease)  {
          
          currentTotal = currentTotal + (decimal) ar.get('amountSum');

        }
        return currentTotal;
    }

    /**
    This calculates the total cost based of leasing unit
     */
    public static Decimal calculateTotalCost(NC_Lease__c lease){

        Integer numberDaysDue = lease.L_Start_Date__c.daysBetween(lease.L_End_Date__c);

        NC_Unit__c unit = [Select id, Revenue__c from NC_Unit__c Where Id =: lease.Unit__c];

        return (numberDaysDue * unit.Revenue__c);

    }

    public static List<NC_Lease__c> getDup(List<NC_Lease__c> newLs){
        

            List<NC_Lease__c> existLs = [Select Id, Contact__c, L_Start_Date__c, L_End_Date__c from NC_Lease__c];
            
            List<NC_Lease__c>  checkedOverlap = haskOverlap(existLs, newLs);
            
 
        return checkedOverlap;
       
    }
     
    public static List<NC_Lease__c> haskOverlap(List<NC_Lease__c> existLs, List<NC_Lease__c> newLs){
        
        
        List<NC_Lease__c> gcErrorList = new List<NC_Lease__c>();
        
             for (NC_Lease__c existL : existLs) {
                for (NC_Lease__c newL : newLs) {

                    if (
                        existL.Contact__c == newL.Contact__c &&
                        (
                            (
                                newL.L_Start_Date__c >= existL.L_Start_Date__c &&
                                newL.L_Start_Date__c <= existL.L_End_Date__c
                            ) ||
                            (
                                newL.L_End_Date__c >= existL.L_Start_Date__c &&
                                newL.L_End_Date__c <= existL.L_End_Date__c
                            )
                        )
                    ) {
                        System.debug('nc2.3>>'+newL);
                        newL.addError('The Contact already has a Graduated Commission on specified dates!');
                        
                        gcErrorList.add(newL);

                    }
                }
            }
        
        return gcErrorList;
    }
}